import = [
    "~/.config/alacritty/tokyonight.toml"
]

[cursor.style]
shape = "Block"

# [env]
# TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = true
blur = true
opacity = 1.0

[colors]
transparent_background_colors = false
